### ISSUE TITLE
The restoration results for LFW-Test, Wider-Test, and WebPhoto-Test are not provided

### ISSUE THREAD

**Issue by sen-mao** [yoqim/waveface#3]
The restoration results for LFW-Test, Wider-Test, and WebPhoto-Test are not provided in [ours](https://drive.google.com/file/d/1m6vAa08rbqsNAjrNJsiUOQCiIAVkSOQo/view?usp=drive_link).

**Comment by yoqim** [comment]
Restoration of real-world datasets have been uploaded.
